### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by KRUBERLICK** [pinterest/homebrew-tap#2]
When running `brew install pinterest/tap/plank` I get the following error:
```
Macs-MBP:agakat-ios KRUBERLICK$ brew install pinterest/tap/plank
==> Installing plank from pinterest/tap
==> Cloning https://github.com/pinterest/plank.git
Updating /Users/KRUBERLICK/Library/Caches/Homebrew/plank--git
==> Checking out tag v1.0
==> unset CC; make archive
Last 15 lines from /Users/KRUBERLICK/Library/Logs/Homebrew/plank/01.unset:
2017-05-13 15:37:55 +0300

unset CC; make archive

xcrun swift build -v -c release -Xswiftc -static-stdlib
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
swift-build: error: Invalid platform path
/Library/Developer/CommandLineTools/usr/bin/swiftc --driver-mode=swift -I /Library/Developer/CommandLineTools/usr/lib/swift/pm -L /Library/Developer/CommandLineTools/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /private/tmp/plank-20170513-9340-fcy4zj/Package.swift -fileno 8
make: *** [archive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pinterest/homebrew-tap/issues
```

**Comment by rahul-malik** [comment]
Thanks for your report!

We build plank from source during installation of Homebrew and it looks like the XCode CLI tools may be missing on your computer. Can you try running `xcode-select --install` to install the tools and then run the `brew install pinterest/tap/plank` command?

**Comment by KRUBERLICK** [comment]
@rahul-malik thanks for an advice! Running `xcode-select --install` returns `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`. I've just bought a new MacBook and have a fresh Xcode installation.

**Comment by rahul-malik** [comment]
Hmm..Just for more context what is the version of XCode and Swift on your MacBook?

I'm assuming you only have one version of XCode on this machine and you've opened it to finish the installation.

**Comment by KRUBERLICK** [comment]
@rahul-malik resetting to the default command line tools path by running `sudo xcode-select -r` helped! Anyways, thanks for your answer :)

**Comment by rahul-malik** [comment]
@KRUBERLICK - glad to hear it works. let me know if you run into any more issues
