### ISSUE TITLE
Unable to install Plank on MacOS High Sierra with Homebrew

### ISSUE THREAD

**Issue by sbatururimi** [pinterest/homebrew-tap#3]
Hi, there.
<img width="541" alt="screen shot 2017-12-15 at 13 54 22" src="https://user-images.githubusercontent.com/1911418/34039176-a6a70736-e19f-11e7-91aa-395af523a87d.png">
Can you help? 
Using 
```
swift build --disable-sandbox
```
throw an error:
```
error: root manifest not found
```

**Comment by rahul-malik** [comment]
@sbatururimi - Looking into this now. Thanks for reporting

**Comment by rahul-malik** [comment]
Working on a fix now, this seems to be a core issue between sandboxing environments between homebrew and swift.

here is the issue on homebrew core for this: https://github.com/Homebrew/homebrew-core/pull/18456

**Comment by rahul-malik** [comment]
Just verified this is fixed now, please try running `brew install pinterest/tap/plank` now
```
==> Installing plank from pinterest/tap
==> Cloning https://github.com/pinterest/plank.git
Updating /Users/rmalik/Library/Caches/Homebrew/plank--git
==> Checking out tag v1.2
==> unset CC; make archive
==> mv .build/release/plank plank
🍺  /usr/local/Cellar/plank/1.2: 5 files, 10.4MB, built in 39 seconds
```
